# CI with maven build and scan
#
# version 1.0.1
#
# see : https://universe.fugerit.org/src/docs/conventions/workflows/build_maven_package.html

name: CI maven build and scan

on:
  # Trigger analysis when pushing in master or pull requests, and when creating
  # a pull request.
  push:
    branches:
      - main
      - develop
      - branch-preview
  pull_request:
    types:
      - opened
      - synchronize
      - reopened

jobs:
  build:
    name: Build
    runs-on: ubuntu-latest
    steps:
      - uses: fugerit-org/psychic-actions/build-maven-package@main