# CI deploy maven package
#
# version 1.0.0
#
# see : https://universe.fugerit.org/src/docs/conventions/workflows/deploy_maven_package.html

name: CI deploy maven package 

on:
  push:
    branches:
    - branch-deploy

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@main
    - name: Set up JDK 17
      uses: actions/setup-java@main
      with:
        java-version: '17'
        distribution: 'corretto'
        cache: maven
    - name: Release Maven package
      uses: samuelmeuli/action-maven-publish@master
      with:
        gpg_private_key: ${{ secrets.GPG_PRIVATE_KEY }}
        gpg_passphrase: ${{ secrets.PASSPHRASE }}
        nexus_username: ${{ secrets.OSS_USERNAME }}
        nexus_password: ${{ secrets.OSS_PASSWORD }}
        maven_args: -P doRelease
